# Generated by Django 5.2.3 on 2025-06-24 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='tamaño',
            field=models.CharField(choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=20),
        ),
        migrations.AlterField(
            model_name='perro',
            name='temperamento',
            field=models.CharField(choices=[('tranquilo', 'Tranquilo'), ('jugueton', 'Juguetón'), ('protector', 'Protector'), ('sociable', 'Sociable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarioadoptante',
            name='preferencias_tamaño',
            field=models.CharField(choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=20),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('adoptado', 'Adoptado')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.perro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.usuarioadoptante')),
            ],
        ),
    ]
