# Generated by Django 5.2.3 on 2025-06-24 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0002_alter_perro_tamaño_alter_perro_temperamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='reservado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adopciones.usuarioadoptante'),
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
