# Generated by Django 5.2.3 on 2025-06-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0003_perro_reservado_por_delete_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='url_imagen',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='estado_salud',
            field=models.CharField(choices=[('sano', 'Sano'), ('tratamiento', 'En tratamiento'), ('recuperacion', 'En recuperación')], max_length=100),
        ),
        migrations.AlterField(
            model_name='perro',
            name='raza',
            field=models.CharField(choices=[('labrador', 'Labrador'), ('beagle', 'Beagle'), ('pastor_aleman', 'Pastor Alemán'), ('poodle', 'Poodle'), ('callejero', 'Callejero')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarioadoptante',
            name='preferencias_raza',
            field=models.CharField(blank=True, choices=[('labrador', 'Labrador'), ('beagle', 'Beagle'), ('pastor_aleman', 'Pastor Alemán'), ('poodle', 'Poodle'), ('callejero', 'Callejero')], max_length=50, null=True),
        ),
    ]
